Adding and re-organizing lattice protocol documentation.
wasmCloud/wasmcloud-dev-site pull request #38
Opened 2021-04-28 20:26 UTC by autodidaddict

2021-04-30 17:19 UTC, autodidaddict commented
ping @brooksmtownsend

2021-04-30 19:41 UTC, brooksmtownsend requested changes
two quick requests

2021-04-30 19:41 UTC, brooksmtownsend commented on content/reference/lattice-protocols/rpc.md
> +is enabled, participants in lattice RPC must conform to a set of standards in order to be able to send and handle messages.
For clarity, perhaps either the title or first mention of RPC should be `Remote Procedure Call (RPC)`

2021-04-30 19:41 UTC, brooksmtownsend commented on content/reference/lattice-protocols/control-interface.md
> -All control interface messages are serialized as _message pack_ payloads that conform to the schema found in the [actor interfaces](https://github.com/wasmcloud/actor-interfaces) repository.
This is a comment for the above line:
```
⚠️ You need to ensure that your namespace prefix does not contain any characters that cannot appear in a NATS subject.
```
We don't want to be in the business of keeping a full list of not-allowed things, but could we say something like "Combinations of ASCII letters and numbers are an example of valid characters for NATS subjects" or point out any common mistakes (no trailing spaces, etc)

2021-05-03 15:45 UTC, brooksmtownsend approved these changes
I like it

2021-05-03 17:11 UTC, merged